name: website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Getting the container
        run: |
          docker pull gvegayon/chisocnet-ss:latest

      - name: Running the container
        run: |
          make docker-render

      - name: Adding new files to git
        run: |
          git add .
          git commit -m "Updating the website" && \
            git push
        


    