name: website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load R
        uses: r-lib/actions/setup-r@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        


    